services:
  - type: web
    name: hackurity-website
    runtime: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
